export const STATUS_ACTIVE = 'Active'
export const STATUS_CANCELLED = 'Cancelled'
export const STATUS_CHALLENGED = 'Challenged'
export const STATUS_DISPUTED = 'Disputed'
export const STATUS_EXECUTED = 'Executed'
export const STATUS_REJECTED = 'Rejected'